FROM oven/bun:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application in development mode
CMD ["bun", "run", "dev"]
